stages:
  - test
  - build
  - deploy

test_code:
  image: naeemgtng/run-tests:latest
  stage: test
  artifacts:
    when: always
    paths:
      - pytest_results.txt
    reports:
      junit:
        - report.xml
  variables:
    SKIP_MODEL_LOADING: "1"
    UV_LINK_MODE: copy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "staging"'
      changes:
        - app/**/*
        - .gitlab-ci.yml
        - pytest.ini
        - pyproject.toml
  script:
    - uv sync --all-groups
    - set +e  # â† allow errors without exiting
    - uv run pytest -rA $PWD/app/tests --junitxml=report.xml >> pytest_results.txt
    - echo "Exit code: $?" >> pytest_results.txt
    - set -e
    - |
      if grep -q "100%" pytest_results.txt; then
          # If found, exit with code 0
          exit 0
      else
          # If not found, exit with code 1
          exit 1
      fi



# build:
#   image: ubuntu:latest
#   script:
#     - echo "building"